# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            James Carr
tagline:          'Fast Preservation'
description:      'Personal Blog'
url:              https://carj.github.io/
baseurl:          /

author:
  name:           'James Carr'
  url:            https://twitter.com/JamesPreservica

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
